### ISSUE TITLE
cc control of multiple samples

### ISSUE THREAD

**Issue by y1ds** [rncbc/drumkv1#6]
I`d like to use cc to control parameters of multiple samples. However when you assign a cc to a parameter, sending cc values to it changes the parameter of the currenyl selected sample. 
Which imho is a little bit weird. Is this intentional? what is the reasoning behind it? Would it be possible  to control parameters of different samples with different (or the same) cc?

**Comment by rncbc** [comment]
On 02/07/2017 06:29 PM, y1ds wrote:
> I`d like to use cc to control parameters of multiple samples. However
> when you assign a cc to a parameter, sending cc values to it changes the
> parameter of the currenyl selected sample.
> Which imho is a little bit weird. Is this intentional? what is the
> reasoning behind it? Would it be possible to control parameters of
> different samples with different (or the same) cc?
> 

yes that's true and it's like so by design.

for one, MIDI controllers are anchored to LV2 plugin control ports and
these are a static set of control values or parameters and they apply to
the currently selected key element or sample, if you prefer.

there's this one control port (GEN1_SAMPLE) that may work for automating
the current selected key or sample, but i'm afraid it doesn't work well
all the time for all hosts, let alone if it works at all :)

making any other way is beyond any future plans on this humble side, so
sorry to tell

cheers
-- 
rncbc aka. Rui Nuno Capela
rncbc@rncbc.org
